# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=170, unique=True)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("price_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("facilities", models.TextField(help_text="Comma separated facilities list.")),
                ("image_url", models.URLField(blank=True)),
                ("available_start_time", models.TimeField(default="07:00:00")),
                ("available_end_time", models.TimeField(default="22:00:00")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="field_management.category",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="VenueAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="field_management.venue",
                    ),
                ),
            ],
            options={"ordering": ["start_datetime"], "verbose_name_plural": "Venue availabilities"},
        ),
    ]
